name: Conditional Workflow

on:
  push:
    branches: [main, develop, feature/*]
  workflow_dispatch: # this allows to run workflow manually on github

jobs:
  detect:
    runs-on: ubuntu-latest
    env:
      VARIABLE: "Example variable value"
    steps:
      - name: Detect branch
        run: |
          echo "VARIABLE is $VARIABLE"
          echo "Actual branch: ${{ github.ref_name }}"
