name: Python App Workflow

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ./python-app
        run: |
          pip install -r requirements.txt

      - name: Run tests
        working-directory: ./python-app
        run: |
          pytest tests/ -v

      - name: Run coverage tests
        working-directory: ./python-app
        run: |
          pytest --cov=app --cov-report=term --cov-report=html

      - name: Save report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
